apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: cb2f3c4455ddb1bf726865c4614fa50de3e141ee
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/group4-app-frontend
  labels:
    app.kubernetes.io/name: group-4-frontend
  name: group-4-frontend-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: group-4-frontend
    app.kubernetes.io/name: group-4-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: cb2f3c4455ddb1bf726865c4614fa50de3e141ee
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/group4-app-frontend
  labels:
    app: group-4-frontend
    app.kubernetes.io/name: group-4-frontend
  name: group-4-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group-4-frontend
      app.kubernetes.io/name: group-4-frontend
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: cb2f3c4455ddb1bf726865c4614fa50de3e141ee
        app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/group4-app-frontend
      labels:
        app: group-4-frontend
        app.kubernetes.io/name: group-4-frontend
    spec:
      containers:
      - image: quay.io/cayops/group-4-frontend:cb2f3c4455ddb1bf726865c4614fa50de3e141ee
        name: react-app
        ports:
        - containerPort: 3000
      securityContext:
        runAsGroup: 1000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: cb2f3c4455ddb1bf726865c4614fa50de3e141ee
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/group4-app-frontend
  labels:
    app.kubernetes.io/name: group-4-frontend
  name: group-4-frontend-route
spec:
  to:
    kind: Service
    name: group-4-frontend-service
